openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - magic-8-controller
      operationId: getAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
  /word:
    get:
      tags:
        - word-controller
      operationId: getWordAndDef
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Definition'
  /quote:
    get:
      tags:
        - quote-controller
      operationId: getQuoteOfTheDay
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Question:
      type: object
      properties:
        question:
          type: string
    Answer:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
        id:
          type: integer
          format: int32
    Definition:
      type: object
      properties:
        id:
          type: integer
          format: int32
        word:
          type: string
        definition:
          type: string
    Quote:
      type: object
      properties:
        id:
          type: integer
          format: int32
        author:
          type: string
        quote:
          type: string
